const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');const fs=require('fs');const path=require('path');const check=(ok,msg)=>{if(!ok)throw Error(msg)};
(async()=>{const out=process.env.FORTUNE_SCREENSHOT_DIR||'work/sources-visuals-validation';fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});try{const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.FORTUNE_TEST_URL||'http://127.0.0.1:8766');
const tab=async name=>page.getByRole('tab',{name,exact:true}).click();const done=async selector=>page.waitForFunction(s=>document.querySelector(s).textContent==='已完成。',selector);
await tab('塔罗问答');await page.locator('#question').fill('合成视觉验收：学习安排');await page.locator('#spread').selectOption('five');await page.locator('#tarot-shuffle').click();await page.waitForFunction(()=>document.querySelectorAll('#tarot-grid button').length===78);check(await page.locator('.back-emblem').count()===78,'backs not styled');for(let i=0;i<5;i++)await page.locator('#tarot-grid button').nth(i).click();await page.locator('#submit').click();await done('#status');await page.waitForFunction(()=>[...document.querySelectorAll('#result .tarot-art')].every(x=>x.complete&&x.naturalWidth>0));check(await page.locator('#result .tarot-art').count()===5,'card images incomplete');
const allCardURLs=await page.evaluate(()=>{const ids=[...Array(22)].map((_,n)=>'major-'+String(n).padStart(2,'0'));for(let s=1;s<=4;s++)for(let n=1;n<=14;n++)ids.push(s+'-'+String(n).padStart(2,'0'));return ids;});for(const id of allCardURLs){const response=await page.request.get(new URL('/assets/tarot/'+id+'.svg',page.url()).href);check(response.status()===200,'missing image '+id);}
await page.evaluate(async()=>{await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})));});await page.screenshot({path:path.join(out,'tarot-art-desktop.png'),fullPage:true});
await tab('西方占星');await page.locator('#chart-birth').fill('2000-01-01T12:00');await page.locator('#chart-offset').fill('+00:00');await page.locator('#chart-zone').fill('Europe/London');await page.locator('#chart-lat').fill('51.4779');await page.locator('#chart-lon').fill('0');await page.locator('#chart-submit').click();await done('#chart-status');await page.locator('#chart-result > details').filter({hasText:'查看星盘、宫位与相位'}).locator('summary').first().click();
check(await page.locator('.planet-target').count()===10,'wheel missing bodies');check(await page.locator('.aspect-lines line').count()>0,'missing aspect lines');check(await page.locator('.astro-planet-list button').count()===10,'planet navigation incomplete');
const overlaps=await page.locator('.planet-target circle').evaluateAll(nodes=>{const points=nodes.map(n=>({x:+n.getAttribute('cx'),y:+n.getAttribute('cy'),r:+n.getAttribute('r')}));return points.some((a,i)=>points.slice(i+1).some(b=>Math.hypot(a.x-b.x,a.y-b.y)<a.r+b.r+1));});check(!overlaps,'planet labels overlap');
await page.locator('.astro-planet-list button').filter({hasText:'太阳'}).click();check((await page.locator('.astro-focus').textContent()).includes('摩羯'),'planet click not grounded');check(await page.locator('.astro-planet-list button[aria-pressed=true]').count()===1,'selection ambiguous');await page.getByRole('checkbox',{name:'显示主要相位连线'}).uncheck();check(await page.locator('.aspect-lines').isHidden(),'aspect toggle broken');await page.getByRole('checkbox',{name:'显示主要相位连线'}).check();
await page.locator('.planet-target').first().focus();await page.keyboard.press('Enter');check(await page.locator('.planet-target[aria-pressed=true]').count()===1,'keyboard activation failed');
const downloadWait=page.waitForEvent('download');await page.getByRole('button',{name:'下载星盘 SVG'}).click();const d=await downloadWait;await d.saveAs(path.join(out,'synthetic-star-chart.svg'));check(fs.readFileSync(path.join(out,'synthetic-star-chart.svg'),'utf8').includes('本命星盘'),'export empty');await page.getByRole('button',{name:'全部天体',exact:true}).click();await page.screenshot({path:path.join(out,'astrology-interactive.png'),fullPage:true});
await tab('紫微斗数');await page.locator('#chart-offset').fill('+08:00');await page.locator('#chart-zone').fill('Asia/Shanghai');await page.locator('#chart-gender').selectOption('female');await page.locator('#chart-submit').click();await done('#chart-status');check((await page.locator('#chart-result .result-summary').textContent()).includes('统筹'),'offline explanation lacks sources');check(await page.locator('#chart-result .result-summary a[href*=oldid]').count()>0,'offline fixed citation missing');const evidence=page.locator('#chart-result > details').filter({hasText:'按宫位查看原文依据'});await evidence.locator('summary').first().click();await page.getByRole('combobox',{name:'紫微原文宫位筛选'}).selectOption('命宫');check((await page.locator('.source-retrieval').textContent()).includes('紫微屬土'),'source mismatch');check(await page.locator('.source-retrieval a[href*=oldid]').count()>0,'source revision missing');await page.screenshot({path:path.join(out,'ziwei-evidence.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});for(const name of ['塔罗问答','西方占星','紫微斗数']){await tab(name);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile overflow '+name);await page.screenshot({path:path.join(out,'mobile-'+name+'.png'),fullPage:true});}
check(errors.length===0,errors.join('\n'));console.log('78 local card assets, source-linked Zi Wei, accessible interactive astrology, SVG export and mobile layout passed.');}finally{await browser.close();}})().catch(e=>{console.error(e.stack);process.exit(1)});
